/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_BLAS */

#ifndef _Included_com_jni_BLAS
#define _Included_com_jni_BLAS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_BLAS
 * Method:    vxm_minPlus
 * Signature: ([I[I[D[I[DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_jni_BLAS_vxm_1minPlus
  (JNIEnv *, jobject, jintArray, jintArray, jdoubleArray, jintArray, jdoubleArray, jint, jint);

/*
 * Class:     com_jni_BLAS
 * Method:    vxm_plusTimes
 * Signature: ([I[I[D[I[DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_jni_BLAS_vxm_1plusTimes
  (JNIEnv *, jobject, jintArray, jintArray, jdoubleArray, jintArray, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
